#!/usr/bin/perl
use warnings;
use strict;

open(FACTER, "facter operatingsystem |") or die "$!\n";
my $operatingsystem = <FACTER>;
chomp($operatingsystem);
close(FACTER);

open(FACTER, "facter operatingsystemrelease |") or die "$!\n";
my $operatingsystemrelease = <FACTER>;
chomp($operatingsystemrelease);
close(FACTER);

my $output_file = "${operatingsystem}-${operatingsystemrelease}.yaml";

my %packages;
open(RPM,"rpm -qa --queryformat '%{NAME} %{VERSION} %{RELEASE}\n' |") or die "$!\n";
while(<RPM>) {
  chomp;
  my ($name, $version, $release) = split(/\s+/, $_, 3);
  if ($name eq 'gpg-pubkey') {
    $packages{"${name}-${version}-${release}"} = 'installed';
  }
  else {
    $packages{$name} = "${version}-${release}";
  }
}
close(RPM);

open(OUTPUT,">$output_file") or die "$!\n";
print OUTPUT "system:\n";
print OUTPUT "  packages:\n";
foreach my $name (sort keys %packages) {
  my $ensure = $packages{$name};
  #my $ensure = 'installed';
  printf OUTPUT "    %s:\n", $name;
  printf OUTPUT "      ensure: '%s'\n", $ensure;
}
close(OUTPUT);
