name    'erwbgy-system'
version '0.7.4'
author 'erwbgy'
license 'Apache License, Version 2.0'
summary 'Manage Linux system resources and services from hiera configuration'
project_page 'https://github.com/erwbgy/puppet-system'
dependency 'erwbgy/limits', '>= 0.3.1'
dependency 'erwbgy/ntp', '>= 0.7.1'
dependency 'domcleal/augeasproviders', '>= 0.5.1'
dependency 'puppetlabs/stdlib', '>= 2.6.0'
dependency 'puppetlabs/concat', '>= 0.2.0'
