#!/usr/bin/perl
use warnings;
use strict;
use YAML;

open(FACTER, "facter operatingsystem |") or die "$!\n";
my $operatingsystem = <FACTER>;
chomp($operatingsystem);
close(FACTER);

open(FACTER, "facter operatingsystemrelease |") or die "$!\n";
my $operatingsystemrelease = <FACTER>;
chomp($operatingsystemrelease);
close(FACTER);

my $output_file = "${operatingsystem}-${operatingsystemrelease}.yaml";

my %packages;
open(RPM,"rpm -qa --queryformat '%{NAME} %{VERSION} %{RELEASE}\n' |") or die "$!\n";
while(<RPM>) {
  chomp;
  my ($name, $version, $release) = split(/\s+/, $_, 3);
  if ($name eq 'gpg-pubkey') {
    $packages{'system::packages'}{"${name}-${version}-${release}"}{'ensure'}
      = 'installed';
  }
  else {
    $packages{'system::packages'}{$name}{'ensure'}
      = "${version}-${release}";
  }
}
close(RPM);

YAML::DumpFile($output_file, \%packages);
